/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.mythesis.view;

import it.unibas.mythesis.Application;
import it.unibas.mythesis.Constant;

import javax.swing.*;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetAdapter;
import java.awt.dnd.DropTargetDropEvent;
import java.io.File;
import java.io.IOException;
import java.util.List;

/**
 *
 * @author raffa
 */
public class MetadataPanel extends javax.swing.JDialog {

    /**
     * Creates new form MetadataPanel
     * @param frameView
     */
    public MetadataPanel(FrameView frameView) {
        super(frameView, true);
    }
    
    public void initialize(){
        initComponents();
        initLabels();
        initActions();
    }
    
    public void open() {
        this.pack();
        this.setLocationRelativeTo(this.getParent());
        this.setVisible(true);
    }
    
    public void close(){
        this.setVisible(false);
    }
    
    private void initLabels(){
        this.welcomeLabel.setText("DROP below the PDF file to extract metadata!");
        this.filePathLabel.setText("**DROP HERE**");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        analizePDFButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        scrollPanelDrop = new JScrollPane();
        filePathLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("DROP below");

        analizePDFButton.setText("Estrai i metadati");
        analizePDFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizePDFButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Chiudi");

        filePathLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filePathLabel.setText("DROP here");
        scrollPanelDrop.setViewportView(filePathLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPanelDrop)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(analizePDFButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analizePDFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analizePDFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizePDFButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analizePDFButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizePDFButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel filePathLabel;
    private JScrollPane scrollPanelDrop;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

    private void initActions(){
        this.analizePDFButton.setAction(Application.getInstance().getMetadataPanelControl().getAnalizePDFAction());
        this.closeButton.setAction(Application.getInstance().getMetadataPanelControl().getCloseAction());
        
        var mdtl = new MyDropTargetListener(scrollPanelDrop);
    }

    public JScrollPane getPannelloDrop(){
        return scrollPanelDrop;
    }

    public void setFilePathLabel(String text){
        this.filePathLabel.setText(text);
    }

    
    private class MyDropTargetListener extends DropTargetAdapter {

        private final DropTarget dropTarget;
        private final JScrollPane scrollPanel;
        
        public MyDropTargetListener(JScrollPane panel){
            this.scrollPanel = panel;
            
            dropTarget = new DropTarget(scrollPanel, DnDConstants.ACTION_COPY, this, true, null);
        }

        public void drop(DropTargetDropEvent event) {
            event.acceptDrop(DnDConstants.ACTION_COPY);
            Transferable transferable = event.getTransferable();
            DataFlavor[] flavors = transferable.getTransferDataFlavors();       //DataFlavors -> forniscono METADATI
            for (DataFlavor flavor : flavors) {
                if (flavor.isFlavorJavaFileListType()) {
                List<File> files = null;
                    try {
                        files = (List<File>) transferable.getTransferData(flavor);
                        for (File file : files) {
                            String percorso = file.getPath();
                            int lunghezza = percorso.length();
                            System.out.println(lunghezza);
                            if (percorso.charAt(lunghezza - 1) != 'f' ||
                                percorso.charAt(lunghezza - 2) != 'd' ||
                                percorso.charAt(lunghezza - 3) != 'p') {
                                Application.getInstance().getFrameView().showErrorMessage("The application only interacts with PDF format files, try again.");
                                return;
                            }
                        }
                    } catch (UnsupportedFlavorException ex) {
                        System.out.println("file not supported.");
                    } catch (IOException ex) {
                        System.out.println("Loading problems.");
                    }
                    for (File file : files) {
                        Application.getInstance().getModel().putBean(Constant.PATH, file.getPath());
                        //Mia aggiunta (ELIMINABILE) -> (Controllare in MetadataPanelControl)
                        Application.getInstance().getModel().putBean(Constant.PARENT_PATH, file.getParent());
                        //Fin qui
                        System.out.println(Application.getInstance().getModel().getBean(Constant.PATH));
                        Application.getInstance().getMetadataPanel().setFilePathLabel(file.getPath());
                    }
                }
            }
        }
    }
}
